### ISSUE TITLE
Lead cannot retrieve history message

### ISSUE THREAD

**Issue by WatsonFungHK** [nhagen/react-intercom#48] opened 2018-06-11 10:22 UTC
Leads are visitors who have interacted with Intercom, like said something in intercom

But my leads cannot access the channel they created before.

Is it because this package does not handle cookies to retrieve it?

**Comment by nhagen** [comment] 2018-10-25 15:32
This package doesn't really do a whole lot--it definitely should not interfere with cookies. Were you able to figure this out?

Closing since I can't reproduce. If you can share any further details to help reproduce this, we can hopefully address whatever the issue is.

**Closed by nhagen** 2018-10-25 15:32 UTC
