### ISSUE TITLE
Cannot resolve module 'prop-types' in ......./node_modules/react-intercom/lib

### ISSUE THREAD

**Issue by leonielindo** [nhagen/react-intercom#30] opened 2017-05-04 15:25 UTC
Currently using react ^15.4.2.
I added import Intercom from 'react-intercom';  added nothing else as I wanted to make sure the page renders with this new addition but got the console error message:

Cannot resolve module 'prop-types' in ......./node_modules/react-intercom/lib 

its referring to line 16: var _propTypes = require('prop-types');

**Comment by blindingstars** [comment] 2017-05-05 02:00
@leonielindo Our team ran into issues with this too; something seems to have broken in the latest update. Running a previous version (`npm i react-intercom@1.0.11 --save`), we were able to install the package. Could help in the meantime!

**Comment by nhagen** [comment] 2017-05-05 03:14
Sorry about this--the issue is that `prop-types` is listed as a devDependency in `package.json`, so its not getting installed with the package. I'll get to this tomorrow and push a new version.

**Comment by leonielindo** [comment] 2017-05-05 09:58
@blindingstars thank you for the recommendation, I will use version 1.0.11 for now and until @nhagen pushes the new version thank you both for getting back to me so quickly.

**Comment by nhagen** [comment] 2017-05-08 16:44
This should be fixed in 1.0.13. Let me know if anyone is still seeing this.

**Closed by nhagen** 2017-05-08 16:44 UTC
